version: "1.0.0"
services:
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: mysql:8.0.21
    ports: 
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_ALLOW_EMPTY_PASSWORD: yes
      # MYSQL_DATABASE: 'flask_app'
    volumes:
      # - ./db:/docker-entrypoint-initdb.d/:ro
      - mydatabase:/var/lib/mysql
      #there mydatabase is a volume that is created in local pc using terminal

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8077:80
    environment:
      #- PMA_ARBITRARY=1
      - PMA_HOST=db
    depends_on:
      - db

volumes:
  mydatabase:
    driver: local