version: "4.17"

services: 
  flask-app-container:
    image: "flask:2.2.3"
    # container-name: flask-backend
    build: .
    depends_on:
      - mysqldb
    ports: 
      - 80:3000


  mysqldb:
    image: "mysql"
    restart: always
    # container_name: mysql-flask-app-container
    ports: 
      - "3306:3306"
    environment: 
        MYSQL_USER: 'root'
        MYSQL_PASSWORD: ''
        MYSQL_ROOT_PASSWORD: '' 
        MYSQL_DATABASE: 'flask_app'
    volumes:
      - db-data:/var/lib/mysql

